import { useState, useEffect } from 'react';
import { ChevronRight, ChevronDown, Plus, X, Check, Lock, RefreshCw, User, Calendar, FileText, Heart, Users, Target, School } from 'lucide-react';

const SUPABASE_URL = 'https://igkwugfefllkutthnjwi.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlna3d1Z2ZlZmxsa3V0dGhuandpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgxNTUxMTIsImV4cCI6MjA4MzczMTExMn0.w9vE39YSYiwGRl9saT9pUpde57XMTTyUjDw-v2sc12o';

const supabase = {
  from: (t) => ({
    select: async () => { const r = await fetch(`${SUPABASE_URL}/rest/v1/${t}?select=*&order=id.desc`, { headers: { 'apikey': SUPABASE_KEY, 'Authorization': `Bearer ${SUPABASE_KEY}` } }); return { data: await r.json(), error: r.ok ? null : 'err' }; },
    insert: async (rows) => { const r = await fetch(`${SUPABASE_URL}/rest/v1/${t}`, { method: 'POST', headers: { 'apikey': SUPABASE_KEY, 'Authorization': `Bearer ${SUPABASE_KEY}`, 'Content-Type': 'application/json', 'Prefer': 'return=representation' }, body: JSON.stringify(rows) }); return { data: await r.json(), error: r.ok ? null : 'err' }; },
    update: (row) => ({ eq: async (c, v) => { await fetch(`${SUPABASE_URL}/rest/v1/${t}?${c}=eq.${v}`, { method: 'PATCH', headers: { 'apikey': SUPABASE_KEY, 'Authorization': `Bearer ${SUPABASE_KEY}`, 'Content-Type': 'application/json' }, body: JSON.stringify(row) }); } }),
    delete: () => ({ eq: async (c, v) => { await fetch(`${SUPABASE_URL}/rest/v1/${t}?${c}=eq.${v}`, { method: 'DELETE', headers: { 'apikey': SUPABASE_KEY, 'Authorization': `Bearer ${SUPABASE_KEY}` } }); } })
  })
};

const diagAssess = { ABA: ['FBA','VB-MAPP','ABLLS-R','Vineland-3'], Psychiatry: ['DSM-5','ADOS-2','Medical Review'], Psychology: ['ADOS-2','ADI-R','WISC-V'], SLP: ['CELF-5','PLS-5','PPVT-4'], OT: ['Sensory Profile','BOT-2','PDMS-2'] };
const swAssess = ['SES Assessment','Eco-Map','Genogram','Family Needs','CANS'];
const itpDisc = ['Psychiatry','Psychology','ABA','SLP','OT','Social Work'];
const schoolSupports = ['Classroom modifications','AAC supports','Behavioral strategies','Sensory accommodations','Academic adaptations','Joint data collection'];
const caregiverFreq = ['Weekly check-in (SW)','Bi-weekly review (ABA/SLP/OT)','Monthly MDT meeting'];
const meetingTypes = ['Team Huddle & Case Consultation', 'Comprehensive Case Review', 'Outcome Evaluation & Program Review', 'Clinical Supervision & Training Updates', 'Family Advisory Council'];
const frequencies = ['Weekly', 'Bi-Weekly', 'Monthly', 'Quarterly'];
const attendeeRoles = ['Medical Director', 'Clinical Director', 'Psychiatrist', 'Psychologist', 'ABA', 'SLP', 'OT', 'Social Worker', 'Caregivers'];
const meetingAttendees = {
  'Team Huddle & Case Consultation': ['Social Worker', 'ABA', 'SLP', 'OT'],
  'Comprehensive Case Review': ['Psychiatrist', 'Psychologist', 'ABA', 'SLP', 'OT', 'Social Worker'],
  'Outcome Evaluation & Program Review': ['Medical Director', 'Clinical Director', 'Social Worker'],
  'Clinical Supervision & Training Updates': ['Psychiatrist', 'Psychologist', 'ABA', 'SLP', 'OT', 'Social Worker'],
  'Family Advisory Council': ['Medical Director', 'Clinical Director', 'Social Worker', 'Caregivers']
};
const disciplines = ['Care Coordination', 'Psychiatry', 'Psychology', 'ABA', 'SLP', 'OT'];
const measureTypes = ['Percent Correct', 'Frequency', 'Duration', 'Reduction', 'Independence Level'];
const timepoints = ['baseline', '3month', '6month', '9month', '12month'];
const tpLabels = { baseline: 'Baseline', '3month': '3-Mo', '6month': '6-Mo', '9month': '9-Mo', '12month': '12-Mo' };

const emptyITP = () => ({ clinicians: '', careCoordinator: '', assessmentDate: '', goals: [], caregiverTraining: { responsibilities: '', frequency: [] }, schoolCollab: { schoolName: '', teacherName: '', contactInfo: '', existingGoals: '', itpAlignment: '', supports: [], carryover: { skills: '', homeReinforce: '', schoolReinforce: '' }, consentName: '', consentDate: '', consentSigned: false }, signoffs: { parent: { signed: false, date: '' }, socialWorker: { signed: false, date: '' }, psychiatry: { signed: false, date: '' }, psychology: { signed: false, date: '' }, aba: { signed: false, date: '' }, slp: { signed: false, date: '' }, ot: { signed: false, date: '' } }, finalized: false, finalizedDate: '' });
const emptyMeeting = () => ({ patientId: '', patientName: '', date: '', time: '', type: '', frequency: '', location: '', facilitator: '', nextDate: '', nextType: '', status: 'Scheduled', attendees: [], absenceNotes: '', safeguardingConcerns: '', previousActionReview: '', caseReview: disciplines.reduce((a, d) => ({ ...a, [d]: { updates: '', risks: '', actions: '' } }), {}), decisions: '', actionItems: [] });

const toDb = (p) => ({ case_id: p.caseId, first_name: p.firstName, last_name: p.lastName, dob: p.dob || null, primary_dx: p.primaryDx, parent_intake_complete: p.parentIntakeComplete, diagnostic_assessments: p.diagnosticAssessments, social_work_assessments: p.socialWorkAssessments, itp: p.itp, treatment_start_date: p.treatmentStartDate || null });
const fromDb = (r) => ({ id: r.id, caseId: r.case_id || '', firstName: r.first_name || '', lastName: r.last_name || '', dob: r.dob || '', primaryDx: r.primary_dx || '', parentIntakeComplete: r.parent_intake_complete || false, diagnosticAssessments: r.diagnostic_assessments || { ABA: [], Psychiatry: [], Psychology: [], SLP: [], OT: [] }, socialWorkAssessments: r.social_work_assessments || [], itp: r.itp || emptyITP(), treatmentStartDate: r.treatment_start_date || null });
const mtToDb = (m) => ({ patient_id: m.patientId, patient_name: m.patientName, date: m.date, time: m.time, type: m.type, frequency: m.frequency, location: m.location, facilitator: m.facilitator, next_date: m.nextDate, next_type: m.nextType, status: m.status, attendees: m.attendees, absence_notes: m.absenceNotes, safeguarding_concerns: m.safeguardingConcerns, previous_action_review: m.previousActionReview, case_review: m.caseReview, decisions: m.decisions, action_items: m.actionItems });
const mtFromDb = (r) => ({ id: r.id, patientId: r.patient_id, patientName: r.patient_name || '', date: r.date || '', time: r.time || '', type: r.type || '', frequency: r.frequency || '', location: r.location || '', facilitator: r.facilitator || '', nextDate: r.next_date || '', nextType: r.next_type || '', status: r.status || 'Scheduled', attendees: r.attendees || '', absenceNotes: r.absence_notes || '', safeguardingConcerns: r.safeguarding_concerns || '', previousActionReview: r.previous_action_review || '', caseReview: r.case_review || {}, decisions: r.decisions || '', actionItems: r.action_items || [] });

const calcGapValue = (stg, tp) => { const val = parseFloat(stg.data?.[tp]?.value); if (isNaN(val)) return null; if (stg.measureType === 'Percent Correct' || stg.measureType === 'Independence Level') return val; if (stg.measureType === 'Frequency' || stg.measureType === 'Duration') { const target = parseFloat(stg.target); return target > 0 ? Math.min((val / target) * 100, 100) : null; } if (stg.measureType === 'Reduction') { const base = parseFloat(stg.data?.baseline?.value); const mast = parseFloat(stg.target); if (!isNaN(base) && base > mast) return Math.min(((base - val) / (base - mast)) * 100, 100); } return null; };
const classifyGoal = (stg, tp) => { if (stg.mastered) return 'Mastered'; const tpIdx = timepoints.indexOf(tp); if (tpIdx <= 0) return null; const curr = calcGapValue(stg, tp); const prev = calcGapValue(stg, timepoints[tpIdx - 1]); if (curr === null || prev === null) return null; const diff = curr - prev; if (diff <= -10) return 'Regressing'; if (diff >= 10) return 'Progressing'; return 'Maintaining'; };
const calcGap = (itp, tp) => { const stgs = itp?.goals?.flatMap(g => g.shortTermGoals) || []; if (stgs.length === 0) return null; const counts = { Regressing: 0, Maintaining: 0, Progressing: 0, Mastered: 0 }; let n = 0; stgs.forEach(s => { if (s.mastered) { counts.Mastered++; n++; } else { const c = classifyGoal(s, tp); if (c) { counts[c]++; n++; } } }); if (n === 0) return null; return { total: n, regressing: Math.round((counts.Regressing / n) * 100), maintaining: Math.round((counts.Maintaining / n) * 100), progressing: Math.round((counts.Progressing / n) * 100), mastered: Math.round((counts.Mastered / n) * 100) }; };

const GapPie = ({ gap }) => { if (!gap) return <div className="text-center text-slate-400 text-sm py-4">No GAP data yet</div>; const data = [{ l: 'Mastered', v: gap.mastered, c: '#10b981' }, { l: 'Progressing', v: gap.progressing, c: '#3b82f6' }, { l: 'Maintaining', v: gap.maintaining, c: '#f59e0b' }, { l: 'Regressing', v: gap.regressing, c: '#ef4444' }].filter(d => d.v > 0); if (data.length === 0) return <div className="text-center text-slate-400 text-sm py-4">No classified goals</div>; let cum = 0; const slices = data.map(d => { const s = cum; cum += d.v; return { ...d, s, e: cum }; }); const coord = (p) => { const a = (p / 100) * 2 * Math.PI - Math.PI / 2; return { x: 50 + 40 * Math.cos(a), y: 50 + 40 * Math.sin(a) }; }; return (<div className="flex items-center gap-4"><svg viewBox="0 0 100 100" className="w-24 h-24">{slices.map((s, i) => { if (s.v === 100) return <circle key={i} cx="50" cy="50" r="40" fill={s.c} />; const st = coord(s.s), en = coord(s.e); return <path key={i} d={`M50,50 L${st.x},${st.y} A40,40 0 ${s.v > 50 ? 1 : 0},1 ${en.x},${en.y} Z`} fill={s.c} />; })}</svg><div className="space-y-1">{data.map(d => <div key={d.l} className="flex items-center gap-2 text-xs"><div className="w-3 h-3 rounded" style={{ backgroundColor: d.c }} /><span>{d.l}: {d.v}%</span></div>)}<div className="text-xs text-slate-400 mt-1">Total: {gap.total} goals</div></div></div>); };

export default function App() {
  const [patients, setPatients] = useState([]);
  const [meetings, setMeetings] = useState([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [view, setView] = useState('patients');
  const [selPt, setSelPt] = useState(null);
  const [selMt, setSelMt] = useState(null);
  const [section, setSection] = useState('info');
  const [showAdd, setShowAdd] = useState(false);
  const [showAddMt, setShowAddMt] = useState(false);
  const [newPt, setNewPt] = useState({ caseId: '', firstName: '', lastName: '', primaryDx: '' });
  const [newMt, setNewMt] = useState({ patientId: '', date: '', time: '', type: '', frequency: '' });
  const [gapTp, setGapTp] = useState('3month');

  const load = async () => { setLoading(true); try { const { data } = await supabase.from('patients').select(); if (data && Array.isArray(data)) setPatients(data.map(fromDb)); const { data: mData } = await supabase.from('meetings').select(); if (mData && Array.isArray(mData)) setMeetings(mData.map(mtFromDb)); } catch (e) { console.error(e); } setLoading(false); };
  useEffect(() => { load(); }, []);
  const save = async (pt) => { setSaving(true); await supabase.from('patients').update(toDb(pt)).eq('id', pt.id); setSaving(false); };
  const saveMt = async (mt) => { setSaving(true); await supabase.from('meetings').update(mtToDb(mt)).eq('id', mt.id); setSaving(false); };

  const getPhase = (p) => { if (p.treatmentStartDate) return { l: "Treatment", c: "emerald" }; if (!p.parentIntakeComplete) return { l: "Diagnostic", c: "amber" }; if (p.socialWorkAssessments.length < swAssess.length) return { l: "Assessment", c: "blue" }; return Object.values(p.itp.signoffs).every(s => s.signed) ? { l: "Ready", c: "indigo" } : { l: "ITP", c: "violet" }; };
  const phaseBadge = (c) => c === 'amber' ? 'bg-amber-50 text-amber-600' : c === 'blue' ? 'bg-blue-50 text-blue-600' : c === 'violet' ? 'bg-violet-50 text-violet-600' : c === 'emerald' ? 'bg-emerald-50 text-emerald-600' : 'bg-indigo-50 text-indigo-600';

  const updatePt = async (id, u) => { const upd = patients.map(p => p.id === id ? { ...p, ...u } : p); setPatients(upd); const pt = upd.find(p => p.id === id); if (selPt?.id === id) setSelPt(pt); await save(pt); };
  const updateItp = async (id, f, v) => { const pt = patients.find(p => p.id === id); await updatePt(id, { itp: { ...pt.itp, [f]: v } }); };
  const toggleDiag = async (id, disc, a) => { const pt = patients.find(p => p.id === id); const curr = pt.diagnosticAssessments[disc] || []; await updatePt(id, { diagnosticAssessments: { ...pt.diagnosticAssessments, [disc]: curr.includes(a) ? curr.filter(x => x !== a) : [...curr, a] } }); };
  const toggleSW = async (id, a) => { const pt = patients.find(p => p.id === id); const curr = pt.socialWorkAssessments || []; await updatePt(id, { socialWorkAssessments: curr.includes(a) ? curr.filter(x => x !== a) : [...curr, a] }); };
  const toggleSign = async (id, role) => { const pt = patients.find(p => p.id === id); if (pt.itp.finalized) return; const curr = pt.itp.signoffs[role]; await updateItp(id, 'signoffs', { ...pt.itp.signoffs, [role]: { signed: !curr.signed, date: !curr.signed ? new Date().toISOString().split('T')[0] : '' } }); };
  const finalize = async (id) => { await updateItp(id, 'finalized', true); await updateItp(id, 'finalizedDate', new Date().toISOString().split('T')[0]); };
  const unlock = async (id) => { await updateItp(id, 'finalized', false); };

  const addGoal = async (id) => { const pt = patients.find(p => p.id === id); if (pt.itp.finalized) return; const g = { id: Date.now(), discipline: '', domain: '', longTermGoal: '', shortTermGoals: [{ id: Date.now(), goal: '', measureType: 'Percent Correct', target: '80', mastered: false, data: { baseline: { value: '' }, '3month': { value: '' }, '6month': { value: '' }, '9month': { value: '' }, '12month': { value: '' } } }] }; await updateItp(id, 'goals', [...(pt.itp.goals || []), g]); };
  const updateGoal = async (pId, gId, f, v) => { const pt = patients.find(p => p.id === pId); if (pt.itp.finalized) return; await updateItp(pId, 'goals', pt.itp.goals.map(g => g.id === gId ? { ...g, [f]: v } : g)); };
  const removeGoal = async (pId, gId) => { const pt = patients.find(p => p.id === pId); if (pt.itp.finalized) return; await updateItp(pId, 'goals', pt.itp.goals.filter(g => g.id !== gId)); };
  const addSTG = async (pId, gId) => { const pt = patients.find(p => p.id === pId); if (pt.itp.finalized) return; const stg = { id: Date.now(), goal: '', measureType: 'Percent Correct', target: '80', mastered: false, data: { baseline: { value: '' }, '3month': { value: '' }, '6month': { value: '' }, '9month': { value: '' }, '12month': { value: '' } } }; await updateItp(pId, 'goals', pt.itp.goals.map(g => g.id === gId ? { ...g, shortTermGoals: [...g.shortTermGoals, stg] } : g)); };
  const updateSTG = async (pId, gId, sId, f, v) => { const pt = patients.find(p => p.id === pId); await updateItp(pId, 'goals', pt.itp.goals.map(g => g.id === gId ? { ...g, shortTermGoals: g.shortTermGoals.map(s => s.id === sId ? { ...s, [f]: v } : s) } : g)); };
  const updateSTGData = async (pId, gId, sId, tp, v) => { const pt = patients.find(p => p.id === pId); await updateItp(pId, 'goals', pt.itp.goals.map(g => g.id === gId ? { ...g, shortTermGoals: g.shortTermGoals.map(s => s.id === sId ? { ...s, data: { ...s.data, [tp]: { value: v } } } : s) } : g)); };
  const toggleMastered = async (pId, gId, sId) => { const pt = patients.find(p => p.id === pId); await updateItp(pId, 'goals', pt.itp.goals.map(g => g.id === gId ? { ...g, shortTermGoals: g.shortTermGoals.map(s => s.id === sId ? { ...s, mastered: !s.mastered } : s) } : g)); };

  const updateSchoolCollab = async (id, f, v) => { const pt = patients.find(p => p.id === id); await updateItp(id, 'schoolCollab', { ...(pt.itp.schoolCollab || {}), [f]: v }); };
  const toggleSchoolSupport = async (id, sup) => { const pt = patients.find(p => p.id === id); const curr = pt.itp.schoolCollab?.supports || []; await updateSchoolCollab(id, 'supports', curr.includes(sup) ? curr.filter(s => s !== sup) : [...curr, sup]); };
  const toggleCaregiverFreq = async (id, freq) => { const pt = patients.find(p => p.id === id); const curr = pt.itp.caregiverTraining?.frequency || []; await updateItp(id, 'caregiverTraining', { ...(pt.itp.caregiverTraining || {}), frequency: curr.includes(freq) ? curr.filter(f => f !== freq) : [...curr, freq] }); };

  const deletePt = async (id) => { if (confirm('Delete?')) { await supabase.from('patients').delete().eq('id', id); setPatients(patients.filter(p => p.id !== id)); if (selPt?.id === id) setSelPt(null); } };
  const addPatient = async () => { if (!newPt.caseId) return; const pt = { ...newPt, parentIntakeComplete: false, diagnosticAssessments: { ABA: [], Psychiatry: [], Psychology: [], SLP: [], OT: [] }, socialWorkAssessments: [], itp: emptyITP(), treatmentStartDate: null }; const { data } = await supabase.from('patients').insert([toDb(pt)]); if (data?.[0]) setPatients([fromDb(data[0]), ...patients]); setNewPt({ caseId: '', firstName: '', lastName: '', primaryDx: '' }); setShowAdd(false); };
  const allSigned = (p) => Object.values(p.itp.signoffs).every(s => s.signed);

  const addMeeting = async () => { if (!newMt.patientId || !newMt.date) return; const pt = patients.find(p => p.id === parseInt(newMt.patientId)); const presetAttendees = meetingAttendees[newMt.type] || []; const mt = { ...emptyMeeting(), ...newMt, patientId: parseInt(newMt.patientId), patientName: pt ? `${pt.caseId} - ${pt.firstName} ${pt.lastName}` : '', attendees: presetAttendees }; const { data } = await supabase.from('meetings').insert([mtToDb(mt)]); if (data?.[0]) setMeetings([mtFromDb(data[0]), ...meetings]); setNewMt({ patientId: '', date: '', time: '', type: '', frequency: '' }); setShowAddMt(false); };
  const updateMtType = async (id, type) => { const presetAttendees = meetingAttendees[type] || []; const freqMap = { 'Team Huddle & Case Consultation': 'Weekly', 'Comprehensive Case Review': 'Bi-Weekly', 'Outcome Evaluation & Program Review': 'Monthly', 'Clinical Supervision & Training Updates': 'Monthly', 'Family Advisory Council': 'Quarterly' }; await updateMt(id, { type, attendees: presetAttendees, frequency: freqMap[type] || '' }); };
  const toggleAttendee = async (id, role) => { const m = meetings.find(x => x.id === id); const curr = m.attendees || []; const newAttendees = curr.includes(role) ? curr.filter(r => r !== role) : [...curr, role]; await updateMt(id, { attendees: newAttendees }); };
  const updateMt = async (id, u) => { const upd = meetings.map(m => m.id === id ? { ...m, ...u } : m); setMeetings(upd); const mt = upd.find(m => m.id === id); if (selMt?.id === id) setSelMt(mt); await saveMt(mt); };
  const deleteMt = async (id) => { if (confirm('Delete?')) { await supabase.from('meetings').delete().eq('id', id); setMeetings(meetings.filter(m => m.id !== id)); if (selMt?.id === id) setSelMt(null); } };
  const addAction = async (mid) => { const m = meetings.find(x => x.id === mid); await updateMt(mid, { actionItems: [...(m.actionItems || []), { id: Date.now(), action: '', owner: '', deadline: '', status: 'Pending' }] }); };
  const updateAction = async (mid, aid, f, v) => { const m = meetings.find(x => x.id === mid); await updateMt(mid, { actionItems: m.actionItems.map(a => a.id === aid ? { ...a, [f]: v } : a) }); };
  const updateCaseReview = async (mid, disc, f, v) => { const m = meetings.find(x => x.id === mid); await updateMt(mid, { caseReview: { ...m.caseReview, [disc]: { ...m.caseReview[disc], [f]: v } } }); };

  const getHeaderTitle = () => { if (view === 'patients' && selPt) return `${selPt.firstName} ${selPt.lastName}`; if (view === 'meetings' && selMt) return selMt.patientName || 'Meeting'; return 'Bright Minds'; };

  const Input = ({ label, value, onChange, type = 'text', disabled = false, className = '' }) => (<div className={className}><label className="text-xs font-medium text-slate-400 uppercase">{label}</label><input type={type} value={value || ''} onChange={e => onChange(e.target.value)} disabled={disabled} className="w-full mt-1 p-2 bg-slate-50 border-0 rounded-lg text-sm disabled:opacity-50" /></div>);
  const TextArea = ({ label, value, onChange, disabled = false, rows = 2 }) => (<div><label className="text-xs font-medium text-slate-400 uppercase">{label}</label><textarea value={value || ''} onChange={e => onChange(e.target.value)} disabled={disabled} rows={rows} className="w-full mt-1 p-2 bg-slate-50 border-0 rounded-lg text-sm resize-none disabled:opacity-50" /></div>);
  const Section = ({ title, icon: Icon, children, open: defOpen = true }) => { const [open, setOpen] = useState(defOpen); return (<div className="border border-slate-200 rounded-xl mb-3 overflow-hidden"><button onClick={() => setOpen(!open)} className="w-full p-3 bg-slate-50 flex items-center justify-between"><div className="flex items-center gap-2"><Icon className="w-4 h-4 text-slate-500" /><span className="font-medium text-slate-700 text-sm">{title}</span></div>{open ? <ChevronDown className="w-4 h-4 text-slate-400" /> : <ChevronRight className="w-4 h-4 text-slate-400" />}</button>{open && <div className="p-3 border-t border-slate-200">{children}</div>}</div>); };

  if (loading) return <div className="min-h-screen bg-slate-50 flex items-center justify-center"><div className="w-10 h-10 border-4 border-slate-200 border-t-teal-500 rounded-full animate-spin" /></div>;

  return (
    <div className="min-h-screen bg-slate-50">
      <header className="sticky top-0 z-40 bg-white border-b border-slate-200">
        <div className="max-w-6xl mx-auto px-4 h-14 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-teal-500 flex items-center justify-center"><Heart className="w-4 h-4 text-white" /></div>
            <h1 className="font-semibold text-slate-800">{getHeaderTitle()}</h1>
            <div className="flex items-center gap-1 bg-slate-100 p-0.5 rounded-full ml-4">
              <button onClick={() => { setView('patients'); setSelMt(null); }} className={`px-3 py-1 rounded-full text-xs font-medium ${view === 'patients' ? 'bg-white text-slate-800 shadow-sm' : 'text-slate-500'}`}>Patients</button>
              <button onClick={() => { setView('meetings'); setSelPt(null); }} className={`px-3 py-1 rounded-full text-xs font-medium ${view === 'meetings' ? 'bg-white text-slate-800 shadow-sm' : 'text-slate-500'}`}>MDT Meetings</button>
            </div>
          </div>
          <div className="flex items-center gap-2">
            {saving && <span className="text-xs text-slate-400">Saving...</span>}
            <button onClick={load} className="p-2 hover:bg-slate-100 rounded-full"><RefreshCw className="w-4 h-4 text-slate-400" /></button>
            <button onClick={() => view === 'patients' ? setShowAdd(true) : setShowAddMt(true)} className="h-8 px-3 bg-slate-900 text-white text-sm rounded-full flex items-center gap-1"><Plus className="w-4 h-4" />New</button>
          </div>
        </div>
      </header>

      <div className="max-w-6xl mx-auto px-4 py-4 flex gap-4">
        <div className="w-64 flex-shrink-0">
          <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
            <div className="p-3 border-b border-slate-100"><h2 className="font-medium text-slate-700 text-sm">{view === 'patients' ? `Patients (${patients.length})` : `Meetings (${meetings.length})`}</h2></div>
            <div className="max-h-[calc(100vh-180px)] overflow-auto">
              {view === 'patients' ? (patients.length === 0 ? <div className="p-6 text-center text-slate-400 text-sm">No patients</div> : patients.map(pt => { const ph = getPhase(pt); return (<div key={pt.id} onClick={() => { setSelPt(pt); setSection('info'); }} className={`p-3 cursor-pointer border-b border-slate-50 ${selPt?.id === pt.id ? 'bg-slate-50' : 'hover:bg-slate-50'}`}><div className="flex justify-between mb-1"><span className="font-medium text-slate-700 text-sm">{pt.caseId}</span><span className={`text-xs px-2 py-0.5 rounded-full ${phaseBadge(ph.c)}`}>{ph.l}</span></div><p className="text-xs text-slate-400">{pt.firstName} {pt.lastName}</p></div>); })) : (meetings.length === 0 ? <div className="p-6 text-center text-slate-400 text-sm">No meetings</div> : meetings.map(mt => (<div key={mt.id} onClick={() => setSelMt(mt)} className={`p-3 cursor-pointer border-b border-slate-50 ${selMt?.id === mt.id ? 'bg-slate-50' : 'hover:bg-slate-50'}`}><div className="flex justify-between mb-1"><span className="font-medium text-slate-700 text-sm">{mt.type || 'Meeting'}</span><span className={`text-xs px-2 py-0.5 rounded-full ${mt.status === 'Completed' ? 'bg-emerald-50 text-emerald-600' : 'bg-blue-50 text-blue-600'}`}>{mt.status}</span></div><p className="text-xs text-slate-400">{mt.patientName}</p><p className="text-xs text-slate-300 mt-1">{mt.date}</p></div>)))}
            </div>
          </div>
        </div>

        <div className="flex-1">
          {view === 'patients' && !selPt && <div className="bg-white rounded-xl border border-slate-200 p-12 text-center"><FileText className="w-12 h-12 text-slate-300 mx-auto mb-3" /><p className="text-slate-400">Select a patient</p></div>}
          {view === 'meetings' && !selMt && <div className="bg-white rounded-xl border border-slate-200 p-12 text-center"><Calendar className="w-12 h-12 text-slate-300 mx-auto mb-3" /><p className="text-slate-400">Select a meeting</p></div>}

          {view === 'patients' && selPt && (
            <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
              <div className="p-4 border-b border-slate-100 flex justify-between items-center">
                <div><h2 className="text-lg font-semibold text-slate-800">{selPt.caseId} - {selPt.firstName} {selPt.lastName}</h2><p className="text-sm text-slate-400">{selPt.primaryDx || 'No diagnosis'}</p></div>
                <div className="flex items-center gap-2">{selPt.itp.finalized && <span className="text-xs px-2 py-1 bg-emerald-50 text-emerald-600 rounded-full flex items-center gap-1"><Lock className="w-3 h-3" />Finalized</span>}<button onClick={() => deletePt(selPt.id)} className="p-2 hover:bg-red-50 rounded-full"><X className="w-4 h-4 text-slate-400 hover:text-red-500" /></button></div>
              </div>
              <div className="flex border-b border-slate-100">{['info', 'diagnostic', 'assessment', 'itp', 'treatment'].map(tab => (<button key={tab} onClick={() => setSection(tab)} className={`px-4 py-3 text-sm font-medium capitalize ${section === tab ? 'text-slate-800 border-b-2 border-slate-800' : 'text-slate-400'}`}>{tab === 'itp' ? 'ITP' : tab}</button>))}</div>
              <div className="p-4 max-h-[calc(100vh-280px)] overflow-auto">
                {section === 'info' && <div className="grid grid-cols-2 gap-3"><Input label="Case ID" value={selPt.caseId} onChange={v => updatePt(selPt.id, { caseId: v })} /><Input label="First Name" value={selPt.firstName} onChange={v => updatePt(selPt.id, { firstName: v })} /><Input label="Last Name" value={selPt.lastName} onChange={v => updatePt(selPt.id, { lastName: v })} /><Input label="DOB" type="date" value={selPt.dob} onChange={v => updatePt(selPt.id, { dob: v })} /><Input label="Diagnosis" value={selPt.primaryDx} onChange={v => updatePt(selPt.id, { primaryDx: v })} className="col-span-2" /></div>}
                {section === 'diagnostic' && <div className="space-y-4"><div onClick={() => updatePt(selPt.id, { parentIntakeComplete: !selPt.parentIntakeComplete })} className={`p-3 rounded-lg cursor-pointer flex items-center gap-3 ${selPt.parentIntakeComplete ? 'bg-emerald-50' : 'bg-slate-50'}`}><div className={`w-5 h-5 rounded-full flex items-center justify-center ${selPt.parentIntakeComplete ? 'bg-emerald-500' : 'bg-slate-300'}`}>{selPt.parentIntakeComplete && <Check className="w-3 h-3 text-white" />}</div><span className="text-sm">Parent Intake Complete</span></div>{Object.entries(diagAssess).map(([disc, items]) => (<div key={disc}><h4 className="text-xs font-medium text-slate-500 mb-2">{disc}</h4><div className="flex flex-wrap gap-1">{items.map(a => { const done = selPt.diagnosticAssessments[disc]?.includes(a); return <button key={a} onClick={() => toggleDiag(selPt.id, disc, a)} className={`px-2 py-1 rounded text-xs ${done ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>{done && <Check className="w-3 h-3 inline mr-1" />}{a}</button>; })}</div></div>))}</div>}
                {section === 'assessment' && <div><h4 className="text-xs font-medium text-slate-500 mb-2">Social Work Assessments</h4><div className="flex flex-wrap gap-1">{swAssess.map(a => { const done = selPt.socialWorkAssessments.includes(a); return <button key={a} onClick={() => toggleSW(selPt.id, a)} className={`px-2 py-1 rounded text-xs ${done ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>{done && <Check className="w-3 h-3 inline mr-1" />}{a}</button>; })}</div></div>}
                {section === 'itp' && (<div>
                  <Section title="Patient & Clinician Info" icon={User}><div className="grid grid-cols-2 gap-3"><Input label="Clinicians" value={selPt.itp.clinicians} onChange={v => updateItp(selPt.id, 'clinicians', v)} disabled={selPt.itp.finalized} /><Input label="Care Coordinator" value={selPt.itp.careCoordinator} onChange={v => updateItp(selPt.id, 'careCoordinator', v)} disabled={selPt.itp.finalized} /><Input label="Assessment Date" type="date" value={selPt.itp.assessmentDate} onChange={v => updateItp(selPt.id, 'assessmentDate', v)} disabled={selPt.itp.finalized} /></div></Section>
                  <Section title="Treatment Goals" icon={Target}><div className="flex justify-between mb-3"><span className="text-xs text-slate-500">{selPt.itp.goals?.length || 0} goals</span>{!selPt.itp.finalized && <button onClick={() => addGoal(selPt.id)} className="text-xs text-teal-600 flex items-center gap-1"><Plus className="w-3 h-3" />Add</button>}</div>{(!selPt.itp.goals || selPt.itp.goals.length === 0) ? <div className="p-4 bg-slate-50 rounded-lg text-center text-slate-400 text-xs">No goals</div> : selPt.itp.goals.map(g => (<div key={g.id} className="p-3 bg-slate-50 rounded-lg mb-2"><div className="flex gap-2 mb-2"><select value={g.discipline} onChange={e => updateGoal(selPt.id, g.id, 'discipline', e.target.value)} disabled={selPt.itp.finalized} className="px-2 py-1 bg-white rounded text-xs"><option value="">Discipline</option>{itpDisc.map(d => <option key={d}>{d}</option>)}</select><input value={g.domain} onChange={e => updateGoal(selPt.id, g.id, 'domain', e.target.value)} disabled={selPt.itp.finalized} placeholder="Domain" className="flex-1 px-2 py-1 bg-white rounded text-xs" />{!selPt.itp.finalized && <button onClick={() => removeGoal(selPt.id, g.id)} className="text-slate-400 hover:text-red-500"><X className="w-4 h-4" /></button>}</div><textarea value={g.longTermGoal} onChange={e => updateGoal(selPt.id, g.id, 'longTermGoal', e.target.value)} disabled={selPt.itp.finalized} placeholder="Long Term Goal" className="w-full px-2 py-1 bg-white rounded text-xs resize-none h-14 mb-2" /><p className="text-xs text-slate-400 mb-1">Short Term Goals</p>{g.shortTermGoals.map(s => (<div key={s.id} className="p-2 bg-white rounded mb-1"><div className="flex gap-1 mb-1"><input value={s.goal} onChange={e => updateSTG(selPt.id, g.id, s.id, 'goal', e.target.value)} placeholder="Goal" className="flex-1 px-2 py-1 bg-slate-50 rounded text-xs" /><select value={s.measureType} onChange={e => updateSTG(selPt.id, g.id, s.id, 'measureType', e.target.value)} className="px-2 py-1 bg-slate-50 rounded text-xs">{measureTypes.map(m => <option key={m}>{m}</option>)}</select><input value={s.target} onChange={e => updateSTG(selPt.id, g.id, s.id, 'target', e.target.value)} placeholder="Target" className="w-14 px-2 py-1 bg-slate-50 rounded text-xs" /><button onClick={() => toggleMastered(selPt.id, g.id, s.id)} className={`px-2 py-1 rounded text-xs ${s.mastered ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>{s.mastered ? '✓' : 'M'}</button></div><div className="flex gap-1 items-center"><span className="text-xs text-slate-400 w-10">Data:</span>{timepoints.map(tp => <input key={tp} value={s.data?.[tp]?.value || ''} onChange={e => updateSTGData(selPt.id, g.id, s.id, tp, e.target.value)} placeholder={tpLabels[tp]} className="flex-1 px-1 py-0.5 bg-slate-50 rounded text-xs text-center" />)}</div></div>))}{!selPt.itp.finalized && <button onClick={() => addSTG(selPt.id, g.id)} className="text-xs text-slate-400">+ STG</button>}</div>))}</Section>
                  <Section title="Caregiver Training" icon={Users} open={false}><TextArea label="Responsibilities" value={selPt.itp.caregiverTraining?.responsibilities} onChange={v => updateItp(selPt.id, 'caregiverTraining', { ...(selPt.itp.caregiverTraining || {}), responsibilities: v })} disabled={selPt.itp.finalized} /><p className="text-xs text-slate-500 mt-2 mb-1">Frequency</p><div className="space-y-1">{caregiverFreq.map(f => { const sel = selPt.itp.caregiverTraining?.frequency?.includes(f); return <div key={f} onClick={() => !selPt.itp.finalized && toggleCaregiverFreq(selPt.id, f)} className={`p-2 rounded cursor-pointer text-xs flex items-center gap-2 ${sel ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-50'}`}><div className={`w-4 h-4 rounded flex items-center justify-center ${sel ? 'bg-emerald-500' : 'bg-slate-300'}`}>{sel && <Check className="w-3 h-3 text-white" />}</div>{f}</div>; })}</div></Section>
                  <Section title="School Collaboration" icon={School} open={false}><div className="grid grid-cols-2 gap-3 mb-3"><Input label="School" value={selPt.itp.schoolCollab?.schoolName} onChange={v => updateSchoolCollab(selPt.id, 'schoolName', v)} disabled={selPt.itp.finalized} /><Input label="Teacher" value={selPt.itp.schoolCollab?.teacherName} onChange={v => updateSchoolCollab(selPt.id, 'teacherName', v)} disabled={selPt.itp.finalized} /></div><TextArea label="Existing Goals" value={selPt.itp.schoolCollab?.existingGoals} onChange={v => updateSchoolCollab(selPt.id, 'existingGoals', v)} disabled={selPt.itp.finalized} /><TextArea label="ITP Alignment" value={selPt.itp.schoolCollab?.itpAlignment} onChange={v => updateSchoolCollab(selPt.id, 'itpAlignment', v)} disabled={selPt.itp.finalized} /><p className="text-xs text-slate-500 mt-2 mb-1">Supports</p><div className="grid grid-cols-2 gap-1">{schoolSupports.map(sup => { const sel = selPt.itp.schoolCollab?.supports?.includes(sup); return <div key={sup} onClick={() => !selPt.itp.finalized && toggleSchoolSupport(selPt.id, sup)} className={`p-2 rounded cursor-pointer text-xs ${sel ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-50'}`}>{sel && <Check className="w-3 h-3 inline mr-1" />}{sup}</div>; })}</div></Section>
                  <Section title="Sign-offs" icon={FileText}><div className="grid grid-cols-4 gap-2">{[{ k: 'parent', l: 'Parent' }, { k: 'socialWorker', l: 'SW' }, { k: 'psychiatry', l: 'Psych' }, { k: 'psychology', l: 'Psychol' }, { k: 'aba', l: 'ABA' }, { k: 'slp', l: 'SLP' }, { k: 'ot', l: 'OT' }].map(r => { const s = selPt.itp.signoffs[r.k]?.signed; return <button key={r.k} onClick={() => toggleSign(selPt.id, r.k)} disabled={selPt.itp.finalized} className={`p-2 rounded-lg text-left ${s ? 'bg-emerald-50' : 'bg-slate-50'} ${selPt.itp.finalized ? 'opacity-60' : ''}`}><div className="flex items-center gap-2"><div className={`w-4 h-4 rounded-full flex items-center justify-center ${s ? 'bg-emerald-500' : 'bg-slate-300'}`}>{s && <Check className="w-3 h-3 text-white" />}</div><span className="text-xs">{r.l}</span></div>{s && <p className="text-xs text-slate-400 mt-1">{selPt.itp.signoffs[r.k].date}</p>}</button>; })}</div>{!selPt.itp.finalized && allSigned(selPt) && <button onClick={() => finalize(selPt.id)} className="w-full mt-3 py-2 bg-emerald-500 text-white text-sm rounded-lg"><Lock className="w-4 h-4 inline mr-1" />Finalize</button>}{selPt.itp.finalized && <button onClick={() => unlock(selPt.id)} className="w-full mt-3 py-2 bg-slate-200 text-slate-600 text-sm rounded-lg">Unlock</button>}</Section>
                </div>)}
                {section === 'treatment' && (<div className="space-y-4"><div className="p-4 bg-white border border-slate-200 rounded-lg"><div className="flex justify-between items-center mb-3"><h3 className="font-medium text-slate-700">Goal Attainment (GAP)</h3><select value={gapTp} onChange={e => setGapTp(e.target.value)} className="px-2 py-1 bg-slate-50 rounded text-xs">{timepoints.filter(t => t !== 'baseline').map(tp => <option key={tp} value={tp}>{tpLabels[tp]}</option>)}</select></div><GapPie gap={calcGap(selPt.itp, gapTp)} /><div className="mt-3 p-2 bg-slate-50 rounded text-xs text-slate-500"><p><span className="text-red-500">Regressing:</span> ≥10% ↓</p><p><span className="text-amber-500">Maintaining:</span> -9% to +9%</p><p><span className="text-blue-500">Progressing:</span> ≥10% ↑</p><p><span className="text-emerald-500">Mastered:</span> Goal met</p></div></div>{selPt.treatmentStartDate ? <div className="p-6 bg-emerald-50 rounded-lg text-center"><Heart className="w-10 h-10 text-emerald-500 mx-auto mb-2" /><p className="text-emerald-700 font-medium">Treatment Started</p><p className="text-emerald-600 text-sm">{selPt.treatmentStartDate}</p></div> : getPhase(selPt).l === "Ready" ? <button onClick={() => updatePt(selPt.id, { treatmentStartDate: new Date().toISOString().split('T')[0] })} className="w-full py-3 bg-emerald-500 text-white font-medium rounded-lg">Start Treatment</button> : <div className="p-6 bg-slate-50 rounded-lg text-center text-slate-400">Complete ITP first</div>}</div>)}
              </div>
            </div>
          )}

          {view === 'meetings' && selMt && (
            <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
              <div className="p-4 border-b border-slate-100 flex justify-between items-center">
                <div><h2 className="text-lg font-semibold text-slate-800">{selMt.type || 'Meeting'}</h2><p className="text-sm text-slate-400">{selMt.patientName}</p></div>
                <div className="flex items-center gap-2"><select value={selMt.status} onChange={e => updateMt(selMt.id, { status: e.target.value })} className={`px-3 py-1 rounded-full text-xs ${selMt.status === 'Completed' ? 'bg-emerald-50 text-emerald-600' : 'bg-blue-50 text-blue-600'}`}><option>Scheduled</option><option>Completed</option><option>Cancelled</option></select><button onClick={() => deleteMt(selMt.id)} className="p-2 hover:bg-red-50 rounded-full"><X className="w-4 h-4 text-slate-400 hover:text-red-500" /></button></div>
              </div>
              <div className="p-4 max-h-[calc(100vh-200px)] overflow-auto space-y-4">
                <div className="grid grid-cols-3 gap-3"><Input label="Date" type="date" value={selMt.date} onChange={v => updateMt(selMt.id, { date: v })} /><Input label="Time" type="time" value={selMt.time} onChange={v => updateMt(selMt.id, { time: v })} /><div><label className="text-xs font-medium text-slate-400 uppercase">Type</label><select value={selMt.type} onChange={e => updateMtType(selMt.id, e.target.value)} className="w-full mt-1 p-2 bg-slate-50 rounded-lg text-sm"><option value="">Select</option>{meetingTypes.map(t => <option key={t}>{t}</option>)}</select></div><Input label="Location" value={selMt.location} onChange={v => updateMt(selMt.id, { location: v })} /><Input label="Facilitator" value={selMt.facilitator} onChange={v => updateMt(selMt.id, { facilitator: v })} /><div><label className="text-xs font-medium text-slate-400 uppercase">Frequency</label><select value={selMt.frequency} onChange={e => updateMt(selMt.id, { frequency: e.target.value })} className="w-full mt-1 p-2 bg-slate-50 rounded-lg text-sm"><option value="">Select</option>{frequencies.map(f => <option key={f}>{f}</option>)}</select></div></div>
                <div className="p-3 bg-slate-50 rounded-lg"><p className="text-xs font-medium text-slate-500 mb-2">Attendees</p><div className="flex flex-wrap gap-2">{attendeeRoles.map(role => { const isPresent = selMt.attendees?.includes(role); return <button key={role} onClick={() => toggleAttendee(selMt.id, role)} className={`px-3 py-1.5 rounded-full text-xs flex items-center gap-1 ${isPresent ? 'bg-teal-100 text-teal-700' : 'bg-white text-slate-500 border border-slate-200'}`}>{isPresent && <Check className="w-3 h-3" />}{role}</button>; })}</div></div>
                <div className="p-3 bg-slate-50 rounded-lg"><p className="text-xs font-medium text-slate-500 mb-2">Next Meeting</p><div className="grid grid-cols-2 gap-3"><Input label="Date" type="date" value={selMt.nextDate} onChange={v => updateMt(selMt.id, { nextDate: v })} /><div><label className="text-xs font-medium text-slate-400 uppercase">Type</label><select value={selMt.nextType} onChange={e => updateMt(selMt.id, { nextType: e.target.value })} className="w-full mt-1 p-2 bg-white rounded-lg text-sm"><option value="">Select</option>{frequencies.map(f => <option key={f}>{f}</option>)}</select></div></div></div>
                <div className="p-3 bg-slate-50 rounded-lg"><p className="text-xs font-medium text-slate-500 mb-2">Administrative Review</p><div className="grid grid-cols-2 gap-3"><TextArea label="Notes on Absences" value={selMt.absenceNotes} onChange={v => updateMt(selMt.id, { absenceNotes: v })} /><TextArea label="Safeguarding Concerns" value={selMt.safeguardingConcerns} onChange={v => updateMt(selMt.id, { safeguardingConcerns: v })} /><TextArea label="Previous Actions Review" value={selMt.previousActionReview} onChange={v => updateMt(selMt.id, { previousActionReview: v })} className="col-span-2" /></div></div>
                <div className="p-3 bg-slate-50 rounded-lg"><p className="text-xs font-medium text-slate-500 mb-2">Case Review</p>{disciplines.map(d => (<div key={d} className="p-2 bg-white rounded mb-2"><p className="text-xs font-medium text-slate-600 mb-1">{d}</p><div className="grid grid-cols-3 gap-2"><div><label className="text-xs text-slate-400">Updates</label><textarea value={selMt.caseReview?.[d]?.updates || ''} onChange={e => updateCaseReview(selMt.id, d, 'updates', e.target.value)} className="w-full p-1 bg-slate-50 rounded text-xs h-12 resize-none" /></div><div><label className="text-xs text-slate-400">Risks</label><textarea value={selMt.caseReview?.[d]?.risks || ''} onChange={e => updateCaseReview(selMt.id, d, 'risks', e.target.value)} className="w-full p-1 bg-slate-50 rounded text-xs h-12 resize-none" /></div><div><label className="text-xs text-slate-400">Actions</label><textarea value={selMt.caseReview?.[d]?.actions || ''} onChange={e => updateCaseReview(selMt.id, d, 'actions', e.target.value)} className="w-full p-1 bg-slate-50 rounded text-xs h-12 resize-none" /></div></div></div>))}<TextArea label="Decisions Made" value={selMt.decisions} onChange={v => updateMt(selMt.id, { decisions: v })} /></div>
                <div className="p-3 bg-slate-50 rounded-lg"><div className="flex justify-between mb-2"><p className="text-xs font-medium text-slate-500">Action Items</p><button onClick={() => addAction(selMt.id)} className="text-xs text-teal-600"><Plus className="w-3 h-3 inline" /> Add</button></div>{(!selMt.actionItems || selMt.actionItems.length === 0) ? <p className="text-xs text-slate-400 text-center py-2">No actions</p> : selMt.actionItems.map(a => (<div key={a.id} className="p-2 bg-white rounded mb-1 flex gap-2"><input value={a.action} onChange={e => updateAction(selMt.id, a.id, 'action', e.target.value)} placeholder="Action" className="flex-1 px-2 py-1 bg-slate-50 rounded text-xs" /><input value={a.owner} onChange={e => updateAction(selMt.id, a.id, 'owner', e.target.value)} placeholder="Owner" className="w-20 px-2 py-1 bg-slate-50 rounded text-xs" /><input type="date" value={a.deadline} onChange={e => updateAction(selMt.id, a.id, 'deadline', e.target.value)} className="px-2 py-1 bg-slate-50 rounded text-xs" /><select value={a.status} onChange={e => updateAction(selMt.id, a.id, 'status', e.target.value)} className={`px-2 py-1 rounded text-xs ${a.status === 'Completed' ? 'bg-emerald-50 text-emerald-600' : 'bg-slate-50'}`}><option>Pending</option><option>Completed</option></select></div>))}</div>
              </div>
            </div>
          )}
        </div>
      </div>

      {showAdd && <div className="fixed inset-0 bg-black/30 flex items-center justify-center z-50 p-4"><div className="bg-white rounded-xl w-full max-w-md"><div className="p-4 border-b"><h3 className="font-semibold">New Patient</h3></div><div className="p-4 space-y-3"><Input label="Case ID *" value={newPt.caseId} onChange={v => setNewPt({ ...newPt, caseId: v })} /><div className="grid grid-cols-2 gap-3"><Input label="First Name" value={newPt.firstName} onChange={v => setNewPt({ ...newPt, firstName: v })} /><Input label="Last Name" value={newPt.lastName} onChange={v => setNewPt({ ...newPt, lastName: v })} /></div><Input label="Diagnosis" value={newPt.primaryDx} onChange={v => setNewPt({ ...newPt, primaryDx: v })} /></div><div className="p-4 bg-slate-50 flex gap-3"><button onClick={() => setShowAdd(false)} className="flex-1 py-2 bg-white rounded-lg text-sm">Cancel</button><button onClick={addPatient} disabled={!newPt.caseId} className="flex-1 py-2 bg-slate-900 text-white rounded-lg text-sm disabled:opacity-50">Add</button></div></div></div>}
      {showAddMt && <div className="fixed inset-0 bg-black/30 flex items-center justify-center z-50 p-4"><div className="bg-white rounded-xl w-full max-w-md"><div className="p-4 border-b"><h3 className="font-semibold">New Meeting</h3></div><div className="p-4 space-y-3"><div><label className="text-xs font-medium text-slate-400 uppercase">Patient *</label><select value={newMt.patientId} onChange={e => setNewMt({ ...newMt, patientId: e.target.value })} className="w-full mt-1 p-2 bg-slate-50 rounded-lg text-sm"><option value="">Select</option>{patients.map(p => <option key={p.id} value={p.id}>{p.caseId} - {p.firstName}</option>)}</select></div><div><label className="text-xs font-medium text-slate-400 uppercase">Type</label><select value={newMt.type} onChange={e => setNewMt({ ...newMt, type: e.target.value })} className="w-full mt-1 p-2 bg-slate-50 rounded-lg text-sm"><option value="">Select</option>{meetingTypes.map(t => <option key={t}>{t}</option>)}</select></div><div className="grid grid-cols-2 gap-3"><Input label="Date *" type="date" value={newMt.date} onChange={v => setNewMt({ ...newMt, date: v })} /><Input label="Time" type="time" value={newMt.time} onChange={v => setNewMt({ ...newMt, time: v })} /></div></div><div className="p-4 bg-slate-50 flex gap-3"><button onClick={() => setShowAddMt(false)} className="flex-1 py-2 bg-white rounded-lg text-sm">Cancel</button><button onClick={addMeeting} disabled={!newMt.patientId || !newMt.date} className="flex-1 py-2 bg-slate-900 text-white rounded-lg text-sm disabled:opacity-50">Add</button></div></div></div>}
    </div>
  );
}
